version: '2'
services:
  frontend:
    build: ./Frontend
    ports:
      - '3000:3000'
        
  backend:
    build: ./Backend
    ports:
      - '4000:4000'

  mongo:
    image: mongo
    ports:
      - '27017:27017'
